site_name: UK Hackathons

nav:
  - Home: 'index.md'
  - Attending:
    - First time: 'attending/firsttime.md'
    - What to Bring: 'attending/bring.md'
    - What to make: 'attending/projects.md'
    - Judging: 'attending/judging.md'
    - Workshops: 'attending/workshops.md'
    - Transport: 'attending/transport.md' 
  - Events: 'events/index.md'
  - Organise:
    - Getting Started: 'organise/gettingstarted.md'
    - Talking to Other Organisers: 'organise/communication.md'
  - Sponsor: 'sponsor/index.md'  



theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'pink'
  logo:
    icon: computer
